// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxcGuNaQa4MLskDUB2qM1JX5SjDeZB7A',
    appId: '1:832598562419:web:cf8c68c3f2d6f4d161fc06',
    messagingSenderId: '832598562419',
    projectId: 'gas-station-b4c1a',
    authDomain: 'gas-station-b4c1a.firebaseapp.com',
    storageBucket: 'gas-station-b4c1a.firebasestorage.app',
    measurementId: 'G-T7N2E6SPC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wwDzRpUfUCyZOqBRBXLQgy-gQldjPZo',
    appId: '1:832598562419:android:25580b22aeea896e61fc06',
    messagingSenderId: '832598562419',
    projectId: 'gas-station-b4c1a',
    storageBucket: 'gas-station-b4c1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOoVBn8exHCULm-ucj0T6lApHJRUJ0F08',
    appId: '1:832598562419:ios:2965701653fcb00261fc06',
    messagingSenderId: '832598562419',
    projectId: 'gas-station-b4c1a',
    storageBucket: 'gas-station-b4c1a.firebasestorage.app',
    iosBundleId: 'com.example.gas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOoVBn8exHCULm-ucj0T6lApHJRUJ0F08',
    appId: '1:832598562419:ios:2965701653fcb00261fc06',
    messagingSenderId: '832598562419',
    projectId: 'gas-station-b4c1a',
    storageBucket: 'gas-station-b4c1a.firebasestorage.app',
    iosBundleId: 'com.example.gas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOxcGuNaQa4MLskDUB2qM1JX5SjDeZB7A',
    appId: '1:832598562419:web:08f88cf409c0f04261fc06',
    messagingSenderId: '832598562419',
    projectId: 'gas-station-b4c1a',
    authDomain: 'gas-station-b4c1a.firebaseapp.com',
    storageBucket: 'gas-station-b4c1a.firebasestorage.app',
    measurementId: 'G-C7HPX2LCTW',
  );
}
